### PR TITLE
Update to v1.95

### PR DESCRIPTION
**Pull request by LestaD**
* 2015-02-03 (v1.95): by LestaD (http://lestad.net)
 *  + Added Yandex Browser
 *  + Added Vivaldi Browser
 *  + Added Chromium Browser

### CODE REVIEW

**Comment by ChrisTitos** [comment]
This pull request added a namespace to the file. Can this be removed (or changed to a proper namespace)?

**Comment by cbschuld** [comment]
Chris, flat out missed that in the pull request; thanks; removed.  //cbs

**Comment by ChrisTitos** [comment]
It also removed the isTablet check.

I think this pull request used an older version of the code.

**Comment by cbschuld** [comment]
@ChrisTitos - I am going to revert this pull request; it's been a problem on a few fronts and (unfortunately) I will not have time to look at the library for a bit there.  Thanks, Crhsi

**Pull request merged**
